# Site settings
title: RicardoUL
author:
  address:
      street: Montevideo
      town: Montevideo
      postcode: 
      country: Uruguay
  email: anybody@gmail.com
  name: Ricardo Umpiérrez
  title: Full Stack Developer
  twitter_username: 
  github_username:  ricardoul
  phone: 
  repository: https://github.com/ricardoul/jekyll-resume
  website: https://github.com/ricardoul/jekyll-resume
description: > # this means to ignore newlines until "baseurl:"
  v
baseurl: "/resume/" # the subpath of your site, e.g. /blog/
url: "http://ricardoul.github.io" # the base hostname & protocol for your site

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
sass:
    style: :compressed
